version: "3.8"

services:
  web:
    # image: "${WEB_IMAGE}"
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    # build: ./
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/mediafiles
    ports:
      - 8000:8000
    env_file: .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    # restart: unless-stopped
    volumes:
      # - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/html:/var/www/html
    # depends_on:
    #   - api_bolao

  # nginx:
  #   image: "${NGINX_IMAGE}"
  #   volumes:
  #     - static_volume:/usr/src/app/staticfiles
  #     - media_volume:/usr/src/app/mediafiles
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - web

volumes:
  static_volume:
  media_volume:
